# Generated by Django 5.2.13 on 2026-04-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("personas", "0006_vendedor_listas_precios_bloqueadas"),
        ("core", "0001_perfilacceso"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaAdmin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("texto", models.TextField(max_length=2000)),
                ("pagina", models.CharField(blank=True, default="", max_length=255)),
                ("leida", models.BooleanField(db_index=True, default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_admin",
                        to="personas.vendedor",
                    ),
                ),
            ],
            options={"ordering": ["-creado_en", "-id"]},
        ),
    ]

