# Generated by Django 5.2.13 on 2026-10-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notaadmin_resuelto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaadmin',
            name='leida',
            field=models.BooleanField(db_index=True, default=False, help_text='Si es mensaje del usuario: lo leyó administración. Si es staff: siempre True al crear.'),
        ),
        migrations.AlterField(
            model_name='notaadmin',
            name='leida_usuario',
            field=models.BooleanField(db_index=True, default=False, help_text='Si es respuesta de staff: el usuario ya abrió/vio el mensaje.'),
        ),
        migrations.AlterField(
            model_name='notaadmin',
            name='resuelto',
            field=models.BooleanField(db_index=True, default=False, help_text='Mensaje del usuario marcado como resuelto por administración.'),
        ),
    ]
