# Generated by Django 5.2.13 on 2026-04-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('MAN', 'Manual'), ('PED', 'Pedido'), ('COM', 'Compra')], default='MAN', max_length=3),
        ),
    ]
