# Generated by Django 5.2.13 on 2026-04-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendario", "0002_alter_evento_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("MAN", "Manual"),
                    ("PED", "Pedido"),
                    ("COM", "Compra"),
                    ("VEN", "Vencimiento"),
                    ("COB", "Cobro"),
                    ("PAG", "Pago"),
                    ("ENT", "Entrega"),
                ],
                default="MAN",
                max_length=3,
            ),
        ),
    ]

