# Generated by Django 5.2.13 on 2026-04-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendario", "0003_alter_evento_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="hora",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="realizado",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]

