# Generated by Django 5.2.13 on 2026-10-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_evento_hora_realizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
