# Generated by Django 5.2.13 on 2026-04-14 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(db_index=True, max_length=150)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('metodo', models.CharField(max_length=10)),
                ('ruta', models.CharField(max_length=512)),
                ('consulta', models.CharField(blank=True, default='', max_length=512)),
                ('codigo_estado', models.PositiveSmallIntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_actividad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de actividad',
                'verbose_name_plural': 'Registros de actividad',
                'ordering': ['-fecha_hora', '-id'],
                'indexes': [models.Index(fields=['usuario', 'fecha_hora'], name='reg_act_usuario_fecha')],
            },
        ),
    ]
