# Generated by Django 5.2.13 on 2026-04-14 01:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0001_initial'),
        ('personas', '0001_initial'),
        ('productos', '0004_producto_fecha_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente de pago'), ('PAG', 'Pagada')], db_index=True, default='PEN', max_length=3)),
                ('fecha_vencimiento_pago', models.DateField()),
                ('subtotal_lineas', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=6)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pago_movimiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta_pago', to='caja.movimientocaja')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='personas.vendedor')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VentaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_venta', to='productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ventas.venta')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
