# Generated by Django 5.2.13 on 2026-04-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_actualizado_en_venta_actualizado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_vencimiento_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
