# Generated by Django 5.2.13 on 2026-04-18 14:21

from django.db import migrations, models


def _backfill_venta_lineas(apps, schema_editor):
    VentaLinea = apps.get_model("ventas", "VentaLinea")
    for ln in VentaLinea.objects.select_related("producto").iterator(chunk_size=500):
        p = ln.producto
        if not p:
            continue
        VentaLinea.objects.filter(pk=ln.pk).update(
            codigo_snapshot=(p.codigo or "")[:6],
            descripcion_snapshot=(p.descripcion or "")[:255],
        )


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0005_venta_aplica_comision"),
    ]

    operations = [
        migrations.AddField(
            model_name="ventalinea",
            name="codigo_snapshot",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código tal como figuraba al confirmar el pedido (no cambia si editás el producto).",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="ventalinea",
            name="descripcion_snapshot",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Descripción tal como figuraba al confirmar el pedido.",
                max_length=255,
            ),
        ),
        migrations.RunPython(_backfill_venta_lineas, migrations.RunPython.noop),
    ]
