# Generated by Django 5.2.13 on 2026-04-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0006_linea_texto_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="envio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]

