# Generated by Django 5.2.13 on 2026-05-12 20:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_movimientocaja_actualizado_en_and_more'),
        ('personas', '0007_vendedor_grupo'),
        ('ventas', '0008_comision_default_5_no_aplica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='aplica_comision',
            field=models.BooleanField(default=False, help_text='Si aplica, la comisión se calcula sobre el neto y se liquida por mes desde Comisiones (egreso de caja).'),
        ),
        migrations.CreateModel(
            name='ComisionLiquidacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_comision_creadas', to=settings.AUTH_USER_MODEL)),
                ('movimiento_caja', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidacion_comision_pago', to='caja.movimientocaja')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_comision_pago', to='personas.vendedor')),
            ],
            options={
                'ordering': ['-anio', '-mes', '-id'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='comision_liquidacion_pago',
            field=models.ForeignKey(blank=True, help_text='Liquidación de comisión en la que se incluyó este pedido (si ya se pagó al vendedor).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ventas.comisionliquidacionpago'),
        ),
    ]
