# Generated by Django 5.2.13 on 2026-05-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_comision_liquidacion_fecha_opcional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comisionliquidacionpago',
            options={'ordering': ['-creado_en', '-id']},
        ),
        migrations.AddField(
            model_name='venta',
            name='costo_mercaderia_cobro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo de mercadería (Σ cantidad × costo producto) al momento del cobro (congelado).', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='ganancia_cobro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ganancia al cobrar: neto − costo de mercadería (congelada; no se recalcula si cambian costos).', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='neto_cobro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Neto del pedido al momento del cobro (congelado).', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='comisionliquidacionpago',
            name='fecha_liquidacion',
            field=models.DateField(blank=True, help_text='Fecha en que se registró el pago al vendedor (egreso en caja).', null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='aplica_comision',
            field=models.BooleanField(default=False, help_text='Si aplica, la comisión se calcula sobre el neto y se liquida desde Comisiones al pagar al vendedor (egreso de caja).'),
        ),
    ]
