# Generated by Django 5.2 — congela ganancia/costo/neto en pedidos ya pagados sin snapshot.

from decimal import Decimal

from django.db import migrations

from core.money_decimal import q2


def _neto_venta_historica(v) -> Decimal:
    raw = Decimal(v.subtotal_lineas or 0) - Decimal(v.descuento_monto or 0) + Decimal(v.envio or 0)
    return q2(raw if raw > 0 else Decimal("0.00"))


def forwards_backfill_snapshots(apps, schema_editor):
    Venta = apps.get_model("ventas", "Venta")
    VentaLinea = apps.get_model("ventas", "VentaLinea")
    Producto = apps.get_model("productos", "Producto")

    qs = Venta.objects.filter(estado="PAG", ganancia_cobro__isnull=True).order_by("pk")
    for v in qs.iterator(chunk_size=200):
        cm = Decimal("0.00")
        for ln in VentaLinea.objects.filter(venta_id=v.pk).only("cantidad", "producto_id"):
            prod = Producto.objects.filter(pk=ln.producto_id).only("costo").first()
            cu = q2(prod.costo if prod is not None and prod.costo is not None else Decimal("0.00"))
            cm = q2(cm + q2(Decimal(ln.cantidad) * cu))
        net = _neto_venta_historica(v)
        v.neto_cobro = net
        v.costo_mercaderia_cobro = cm
        v.ganancia_cobro = q2(net - cm)
        v.save(update_fields=["neto_cobro", "costo_mercaderia_cobro", "ganancia_cobro"])


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0011_venta_snapshot_ganancia_cobro"),
    ]

    operations = [
        migrations.RunPython(forwards_backfill_snapshots, backwards_noop),
    ]
