# Generated by Django 5.2.13 on 2026-10-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0019_venta_linea_archivo_despacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
