# Generated by Django 5.2.13 on 2026-10-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0020_venta_eliminado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='comision_descontada_en_pedido',
            field=models.BooleanField(default=False, help_text='Si aplica comisión y está activo, el ingreso en caja al cobrar es neto menos comisión.'),
        ),
    ]
