# Generated by Django 5.2.13 on 2026-04-14 02:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0002_movimientocaja_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=120)),
                ('cuenta', models.CharField(help_text='Número de cuenta, CBU, alias u otro identificador.', max_length=120)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuenta bancaria',
                'verbose_name_plural': 'Cuentas bancarias',
                'ordering': ['banco', 'cuenta'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='bancos.cuentabancaria')),
                ('movimiento_caja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gasto_origen', to='caja.movimientocaja')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('credito', models.BooleanField(help_text='Verdadero: ingreso a la cuenta. Falso: egreso.')),
                ('origen', models.CharField(choices=[('CAJ', 'Caja (transferencia / MP)'), ('GAS', 'Gasto'), ('AJU', 'Ajuste manual')], max_length=3)),
                ('concepto', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='bancos.cuentabancaria')),
                ('movimiento_caja', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_bancario', to='caja.movimientocaja')),
            ],
            options={
                'verbose_name': 'Movimiento de cuenta',
                'verbose_name_plural': 'Movimientos de cuenta',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
