# Generated by Django 5.2.13 on 2026-05-26 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeudaCompartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vencimiento', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Deuda compartida',
                'verbose_name_plural': 'Deudas compartidas',
                'ordering': ['vencimiento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CancelacionDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('medio', models.CharField(choices=[('DINERO', 'Dinero'), ('COMPRA', 'Compra'), ('MERCADERIA', 'Mercadería')], default='DINERO', max_length=12)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelaciones', to='cuentas_compartidas.deudacompartida')),
            ],
            options={
                'verbose_name': 'Cancelación de deuda',
                'verbose_name_plural': 'Cancelaciones de deuda',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='deudacompartida',
            name='deudor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deudas_compartidas', to='cuentas_compartidas.negocio'),
        ),
        migrations.CreateModel(
            name='OperacionCompartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('DINERO', 'Dinero'), ('MERCADERIA', 'Mercadería')], default='COMPRA', max_length=12)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_pagadas', to='cuentas_compartidas.negocio')),
            ],
            options={
                'verbose_name': 'Operación compartida',
                'verbose_name_plural': 'Operaciones compartidas',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='deudacompartida',
            name='operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='cuentas_compartidas.operacioncompartida'),
        ),
        migrations.AddConstraint(
            model_name='deudacompartida',
            constraint=models.UniqueConstraint(fields=('operacion', 'deudor'), name='uniq_deuda_por_operacion_deudor'),
        ),
    ]
