# Generated by Django 5.2.13 on 2026-05-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_compartidas', '0002_negocios_iniciales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negocio',
            options={'ordering': ['nombre'], 'permissions': [('access_cuentas_compartidas', 'Puede acceder a cuentas compartidas')], 'verbose_name': 'Negocio', 'verbose_name_plural': 'Negocios'},
        ),
    ]
