# Generated by Django 5.2.13 on 2026-05-26 18:33

from django.db import migrations


def actualizar_nombre_permiso(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.filter(
        content_type__app_label="cuentas_compartidas",
        codename="access_cuentas_compartidas",
    ).update(name="Puede acceder a Gastos compartidos")


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_compartidas', '0003_alter_negocio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negocio',
            options={'ordering': ['nombre'], 'permissions': [('access_cuentas_compartidas', 'Puede acceder a Gastos compartidos')], 'verbose_name': 'Negocio', 'verbose_name_plural': 'Negocios'},
        ),
        migrations.RunPython(actualizar_nombre_permiso, migrations.RunPython.noop),
    ]
