# Generated by Django 5.2.13 on 2026-04-18 14:21

from django.db import migrations, models


def _backfill_presupuesto_lineas(apps, schema_editor):
    PresupuestoLinea = apps.get_model("presupuestos", "PresupuestoLinea")
    for ln in PresupuestoLinea.objects.select_related("producto").iterator(chunk_size=500):
        p = ln.producto
        if not p:
            continue
        PresupuestoLinea.objects.filter(pk=ln.pk).update(
            codigo_snapshot=(p.codigo or "")[:6],
            descripcion_snapshot=(p.descripcion or "")[:255],
        )


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestos", "0005_presupuesto_aplica_comision"),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuestolinea",
            name="codigo_snapshot",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código al guardar la línea (no cambia si editás el producto después).",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="presupuestolinea",
            name="descripcion_snapshot",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Descripción al guardar la línea.",
                max_length=255,
            ),
        ),
        migrations.RunPython(_backfill_presupuesto_lineas, migrations.RunPython.noop),
    ]
