# Generated by Django 5.2.13 on 2026-04-18 14:25

from django.db import migrations, models


def _backfill_capturado(apps, schema_editor):
    PresupuestoLinea = apps.get_model("presupuestos", "PresupuestoLinea")
    for ln in PresupuestoLinea.objects.select_related("producto").iterator(chunk_size=500):
        p = ln.producto
        if not p:
            continue
        PresupuestoLinea.objects.filter(pk=ln.pk).update(producto_capturado_en=p.actualizado_en)


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestos", "0006_linea_texto_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuestolinea",
            name="producto_capturado_en",
            field=models.DateTimeField(
                blank=True,
                help_text="Valor de producto.actualizado_en al último guardado/aceptación de esta línea (para detectar cambios en catálogo).",
                null=True,
            ),
        ),
        migrations.RunPython(_backfill_capturado, migrations.RunPython.noop),
    ]
