# Generated by Django 5.2.13 on 2026-04-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presupuestos", "0007_producto_capturado_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuesto",
            name="envio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]

