# Generated by Django 5.2.13 on 2026-05-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0009_comision_default_5_no_aplica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='aplica_comision',
            field=models.BooleanField(default=False, help_text='Si aplica, al generar el pedido se discrimina la comisión (se liquida por mes desde Comisiones).'),
        ),
    ]
