# Generated by Django 5.2.13 on 2026-05-27 20:29

from django.db import migrations, models


def capturar_precio_inicial(apps, schema_editor):
    PresupuestoLinea = apps.get_model("presupuestos", "PresupuestoLinea")
    for linea in PresupuestoLinea.objects.filter(precio_catalogo_capturado__isnull=True).iterator():
        linea.precio_catalogo_capturado = linea.precio_unitario
        linea.save(update_fields=["precio_catalogo_capturado"])


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0010_comision_help_text_ingreso_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestolinea',
            name='precio_catalogo_capturado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta del producto al guardar/aceptar la línea.', max_digits=12, null=True),
        ),
        migrations.RunPython(capturar_precio_inicial, migrations.RunPython.noop),
    ]
