# Generated by Django 5.2.13 on 2026-10-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0011_presupuestolinea_precio_catalogo_capturado'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
