# Generated by Django 5.2.13 on 2026-04-18 14:11

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


def _slugify_nombre(nombre: str) -> str:
    from django.utils.text import slugify

    return (slugify(nombre)[:120] or "lista").lower()


def forwards_migrar_m2m(apps, schema_editor):
    ListaPrecios = apps.get_model("productos", "ListaPrecios")
    Producto = apps.get_model("productos", "Producto")
    ListaPrecioItem = apps.get_model("productos", "ListaPrecioItem")
    M2M = ListaPrecios.productos.through

    # Slugs y marca Farmacia por nombre
    for lista in ListaPrecios.objects.all():
        if not lista.slug:
            base = _slugify_nombre(lista.nombre)
            slug = base
            n = 1
            while ListaPrecios.objects.filter(slug=slug).exclude(pk=lista.pk).exists():
                slug = f"{base}-{n}"
                n += 1
            lista.slug = slug
        nm = (lista.nombre or "").strip().lower()
        if nm in ("farmacias", "farmacia"):
            lista.es_farmacia = True
        lista.save(update_fields=["slug", "es_farmacia"])

    if not ListaPrecios.objects.filter(es_farmacia=True).exists():
        ListaPrecios.objects.create(
            nombre="Farmacias",
            slug="farmacias",
            es_farmacia=True,
        )

    # Solo listas NO Farmacia: un registro por vínculo con precio copiado del producto
    for row in M2M.objects.all().iterator():
        lista_id = row.listaprecios_id
        producto_id = row.producto_id
        if not lista_id or not producto_id:
            continue
        try:
            lista = ListaPrecios.objects.get(pk=lista_id)
        except ListaPrecios.DoesNotExist:
            continue
        if lista.es_farmacia:
            continue
        try:
            prod = Producto.objects.get(pk=producto_id)
        except Producto.DoesNotExist:
            continue
        precio = prod.precio_venta if prod.precio_venta is not None else Decimal("0")
        ListaPrecioItem.objects.get_or_create(
            lista_id=lista_id,
            producto_id=producto_id,
            defaults={"precio_venta": precio},
        )


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0007_deshabilitar_productos_sin_stock"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listaprecios",
            options={"ordering": ["-es_farmacia", "-creado_en", "-id"]},
        ),
        migrations.AddField(
            model_name="listaprecios",
            name="es_farmacia",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="listaprecios",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=120),
        ),
        migrations.CreateModel(
            name="ListaPrecioItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("precio_venta", models.DecimalField(decimal_places=2, max_digits=12)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "lista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="productos.listaprecios",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_lista_precio",
                        to="productos.producto",
                    ),
                ),
            ],
            options={
                "ordering": ["producto__descripcion", "producto__codigo"],
                "unique_together": {("lista", "producto")},
            },
        ),
        migrations.RunPython(forwards_migrar_m2m, backwards_noop),
        migrations.RemoveField(
            model_name="listaprecios",
            name="productos",
        ),
        migrations.AddField(
            model_name="listaprecios",
            name="productos",
            field=models.ManyToManyField(
                related_name="listas_precios",
                through="productos.ListaPrecioItem",
                to="productos.producto",
            ),
        ),
    ]
