# Generated by Django 5.2.13 on 2026-05-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_producto_deshabilitado_por_stock_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='laboratorio',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
