# Generated by Django 5.2.13

from django.db import migrations, models
from django.utils import timezone


def backfill_precio_actualizado(apps, schema_editor):
    Producto = apps.get_model("productos", "Producto")
    now = timezone.now()
    for p in Producto.objects.all().only("id", "actualizado_en", "creado_en"):
        Producto.objects.filter(pk=p.pk).update(
            precio_actualizado_en=p.actualizado_en or p.creado_en or now
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0011_producto_laboratorio"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="oferta",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_actualizado_en",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_precio_actualizado, noop_reverse),
    ]
