# Generated by Django 5.2.13 on 2026-04-14 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
        ('caja', '0002_movimientocaja_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='bancos.cuentabancaria'),
        ),
    ]
