# Generated by Django 5.2.13 on 2026-10-02 00:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_movimientocaja_actualizado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='es_arqueo',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='saldo_arqueo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso'), ('ARQ', 'Arqueo')], max_length=3),
        ),
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('saldo_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('saldo_transferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('saldo_mercadopago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('saldo_cheque', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('saldo_otro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('observaciones', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arqueos_caja_creados', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arqueo', to='caja.movimientocaja')),
            ],
            options={
                'verbose_name': 'Arqueo de caja',
                'verbose_name_plural': 'Arqueos de caja',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
