# Generated by Django 5.2.13 on 2026-04-14 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0002_movimientocaja_venta'),
        ('personas', '0001_initial'),
        ('productos', '0004_producto_fecha_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('fecha_vencimiento_pedido', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('medio_pago', models.CharField(choices=[('CASH', 'Efectivo'), ('TRF', 'Transferencia'), ('MP', 'MercadoPago'), ('CHQ', 'Cheque'), ('OTH', 'Otro')], default='CASH', max_length=10)),
                ('banco', models.CharField(blank=True, default='', max_length=100)),
                ('numero_cheque', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_vencimiento_cheque', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('movimiento_caja', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compra_origen', to='caja.movimientocaja')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_origen', to='productos.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='personas.proveedor')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
    ]
