# Generated by Django 5.2.13 on 2026-10-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_compra_modo_factura_sin_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='modo',
            field=models.CharField(choices=[('PRO', 'Productos (detalle)'), ('FAC', 'Factura sin detalle')], db_index=True, default='PRO', help_text='PRO: alta con producto y stock. FAC: factura / deuda sin detallar ítems ni egreso en caja.', max_length=3),
        ),
    ]
