# Generated by Django 5.2.13 on 2026-04-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprador',
            name='habilitado',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='habilitado',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='habilitado',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
