# Generated by Django 5.2.13 on 2026-04-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0002_comprador_habilitado_proveedor_habilitado_and_more"),
        ("personas", "0002_vendedor_usuario"),
    ]

    operations = []

