# Generated by Django 5.2.13 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0003_merge_0002_vendedor_usuario_0002_habilitado"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendedor",
            name="acceso",
            field=models.CharField(
                choices=[
                    ("BOTH", "Completo y vendedor"),
                    ("VEND", "Solo vendedor (reducido)"),
                    ("FULL", "Solo completo"),
                ],
                db_index=True,
                default="BOTH",
                max_length=4,
            ),
        ),
    ]

