# Generated by Django 5.2.13 on 2026-04-17 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_vendedor_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprador',
            name='vendedor_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to='personas.vendedor'),
        ),
    ]
