# Generated by Django 5.2.13 on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0009_alter_producto_en_lista_precios_default_false"),
        ("personas", "0005_comprador_vendedor_asignado"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendedor",
            name="listas_precios_bloqueadas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Listas que este vendedor NO puede ver/descargar en el portal vendedor.",
                related_name="vendedores_bloqueados",
                to="productos.listaprecios",
            ),
        ),
    ]

