# Generated by Cursor on 2026-04-27

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0006_vendedor_listas_precios_bloqueadas"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendedor",
            name="es_jefe_grupo",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="Vendedor a cargo de grupo",
            ),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="comision_grupo_porcentaje",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=6,
                verbose_name="Comisión por ventas del grupo (%)",
            ),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="vendedores_a_cargo",
            field=models.ManyToManyField(
                blank=True,
                related_name="jefes_de_grupo",
                symmetrical=False,
                to="personas.vendedor",
                verbose_name="Vendedores a cargo",
            ),
        ),
    ]
