# Generated by Django 5.2.13 on 2026-10-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0008_vendedor_aplica_comision_por_defecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprador',
            name='plazo_pago_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Ejemplo: 20. Al armar un pedido o presupuesto se calcula la fecha límite; después se puede editar.', null=True, verbose_name='Plazo de pago (días)'),
        ),
    ]
